In [1]:
import pandas as pd
import numpy as np

In [32]:
# Series of Reaction Times

# 10 subject's reaction times in milliseconds
rt_series = pd.Series(
    [523, 610, 487, 590, 705, 450, 678, 512, 560, 630],
    name= "ReactionTime_ms"
) # A pandas Series is a one-dimensional labeled array.

# Compute statistics
mean_rt = rt_series.mean() # arithmetic average
median_rt = rt_series.median() # robust central tendency
std_rt = rt_series.std() # sample standard deviation (ddof=1 by default)

mean_rt, median_rt, std_rt

(np.float64(574.5), np.float64(575.0), np.float64(83.16549765377466))

In [33]:
# DataFrame

data = {
    "SubjectID": [f"S{i+1}" for i in range(10)],
    "Age": [22, 25, 19, 24, 30, 21, 27, 23, 26, 28],
    "RT": [523, 610, 487, 590, 705, 450, 678, 512, 560, 630]
} # A DataFrame is a two-dimensional labeled data structure

df = pd.DataFrame(data)

# Inspect structure
print("Head:\n", df.head(), "\n\n")
print("Tail:\n", df.tail(), "\n\n")
print("Info:\n", df.info(), "\n\n")
print("Describe:\n", df.describe(), "\n\n")
print("Dtypes:\n", df.dtypes)

Head:
   SubjectID  Age   RT
0        S1   22  523
1        S2   25  610
2        S3   19  487
3        S4   24  590
4        S5   30  705


Tail:
   SubjectID  Age   RT
5        S6   21  450
6        S7   27  678
7        S8   23  512
8        S9   26  560
9       S10   28  630


<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SubjectID  10 non-null     str
 1   Age        10 non-null     int64
 2   RT         10 non-null     int64
dtypes: int64(2), str(1)
memory usage: 372.0 bytes
Info:
 None


Describe:
              Age          RT
count  10.000000   10.000000
mean   24.500000  574.500000
std     3.374743   83.165498
min    19.000000  450.000000
25%    22.250000  514.750000
50%    24.500000  575.000000
75%    26.750000  625.000000
max    30.000000  705.000000


Dtypes:
 SubjectID      str
Age          int64
RT           int64
dtype: object

In [34]:
# Convert RT from seconds to milliseconds

df["RT"] = df["RT"] / 1000  # convert to seconds artificially

# Convert back to milliseconds:
df["RT_ms"] = df["RT"] * 1000

Note: Always create a new column when transforming units in a research notebook to preserve provenance.

Series and DataFrames are foundational. These structures:  
- Keep variable names and subject identifiers attached to the data.
- Allow fast, column-wise numerical operations without manual loops.
- Handle missing values in a structured and consistent way.
- Work directly with common statistical and machine learning libraries.
- Support fully script-based analyses that can be rerun and reproduced exactly

Note: Indexing and selection are not merely syntactic conveniences; they determine whether preprocessing steps are logically valid. Many analytic errors originate from incorrect subsetting rather than incorrect statistical modeling.

In [24]:
# loc vs iloc

print(df.loc[0, "RT"]) # label-based (row label 0, column RT)
print(df.iloc[0, 2])  # first row, third column by position

0.523
0.523

In [28]:
# Conditional Selection (Boolean Masking)

mask = df["Age"] > 25
print(df[mask])
# or
print(df[(df["Age"] > 25) & (df["RT"] < 600)])

  SubjectID  Age     RT  RT_ms
4        S5   30  0.705  705.0
6        S7   27  0.678  678.0
8        S9   26  0.560  560.0
9       S10   28  0.630  630.0
  SubjectID  Age     RT  RT_ms
4        S5   30  0.705  705.0
6        S7   27  0.678  678.0
8        S9   26  0.560  560.0
9       S10   28  0.630  630.0

  The mask must: 
1. Be the same length as the DataFrame.
2. Be enclosed in parentheses when combined with logical operators.

In [14]:
# Select subjects with Age > 25

df[df["Age"] > 25] # Or df.loc[df["Age"] > 25]: this isolates older participants for subgroup analysis.

  SubjectID  Age     RT  RT_ms
4        S5   30  0.705  705.0
6        S7   27  0.678  678.0
8        S9   26  0.560  560.0
9       S10   28  0.630  630.0

In [31]:
# Filter trials where RT < 200 ms or RT > 2000 ms (between)

df[~df["RT"].between(200,2000)] # Or df[(df["RT"] < 200) | (df["RT"] > 2000)]
# The tilde ~ negates the condition.

  SubjectID  Age     RT  RT_ms
0        S1   22  0.523  523.0
1        S2   25  0.610  610.0
2        S3   19  0.487  487.0
3        S4   24  0.590  590.0
4        S5   30  0.705  705.0
5        S6   21  0.450  450.0
6        S7   27  0.678  678.0
7        S8   23  0.512  512.0
8        S9   26  0.560  560.0
9       S10   28  0.630  630.0

In [30]:
# Checks membership in a set (isin)

print(df[df["SubjectID"].isin(["S1", "S3", "S5"])])

  SubjectID  Age     RT  RT_ms
0        S1   22  0.523  523.0
2        S3   19  0.487  487.0
4        S5   30  0.705  705.0

In [21]:
# Subset columns: only SubjectID and RT

df[["SubjectID", "RT"]] # Double brackets are required because you are passing a list of column names.
# df["SubjectID", "RT"] is incorrect, interpreted as tuple

  SubjectID     RT
0        S1  0.523
1        S2  0.610
2        S3  0.487
3        S4  0.590
4        S5  0.705
5        S6  0.450
6        S7  0.678
7        S8  0.512
8        S9  0.560
9       S10  0.630

Note:
- Always inspect the result with head().
- Confirm row counts before and after filtering.
- Explicitly report filtering criteria in markdown.